apiVersion: v1
kind: Template
labels:
  template: splunk-config
message: |-
  splunk configuration template.
metadata:
  annotations:
    description: |-
      splunk configuration template.
    tags: splunk-config
    template: splunk-config
  name: splunk-config

# Parameters
parameters:
- name: URL
  required: true
  value: "set.url"
  description: Splunk Url without uri /services/collector Eg. http://splunk:8088
- name: TOKEN
  required: true
  value: "set.token"

# Objects
objects:

- apiVersion: v1
  stringData:
    SPLUNK_COLLECTOR_URL: ${URL}
    SPLUNK_TOKEN: ${TOKEN}
  kind: Secret
  metadata:
    name: splunk-config
