name: Main - Build Image and Push to Openshift Registry for Dev Deployment
on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: Select a component Image to deploy
        options:
          - -Select-
          - search-api
          - request-api
          - dynadapter
        required: true
      tag:
        description: "Target image tag to build and deploy"
        required: true
        default: "dev"

jobs:
  build-push-image:
    name: build-push-image
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.tag }}
    env:
      app: ${{github.event.inputs.app}}
      tag: ${{github.event.inputs.tag}}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: .

      - name: Fetch Project Path
        id: fetch_projectpath
        env:
          appname: ${{ env.app }}
        run: >-
          echo ::set-output name=PATH::$(
            jq -r .ProjectMapping.\"${appname}\" ./gitops/projectpathmapping.json
          )

      - name: Print Env Variables
        env:
          PROJECT_PATH: ${{ steps.fetch_projectpath.outputs.PATH }}
        run: |
          echo "Release Environment: Dev"
          echo "Release App: ${{ env.app }}"
          echo "Project Build Path: ${PROJECT_PATH}"
          echo "Release Tag: ${{ env.tag }}"

      # - name: Login to OpenShift Container Repository
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
      #     username: ${{secrets.OPENSHIFT_SA_USERNAME}}
      #     password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Pull Builder Image from OpenShift Container Repository
        #env:
        #  IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/dotnet31-rhel7:sdk-custom
        run: docker pull bitnami/dotnet-sdk:3.1

      - name: Build Application Image using S2I
        id: build_image
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: ./app
          builder_image: bitnami/dotnet-sdk:3.1
          image: ${{ env.app}}
          tags: ${{ env.tag }}
          env_vars: |
            DOTNET_STARTUP_PROJECT=${{ steps.fetch_projectpath.outputs.PATH }}
            DOTNET_CONFIGURATION=Release
            DOTNET_PACK=true
            WORKDIR=/opt/app-root/src
            DOTNET_INCREMENTAL=true
            DOTNET_RESTORE_CONFIGFILE=./NuGet.config
            NEXUS_REPO_USER=${{ secrets.NEXUS_REPO_USER }}
            NEXUS_REPO_PASSWORD=${{ secrets.NEXUS_REPO_PASSWORD }}
            NEXUS_REPO_URL=${{ secrets.NEXUS_REPO_URL }}

      #- name: Push Application Image to Openshift ImageStream & Deploy to Dev
      #  env:
      #    SOURCE_IMAGE: ${{ env.app}}:${{ env.tag }}
      #    TARGET_IMAGE: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_TOOLS_NAMESPACE}}/${{ env.app}}:${{ env.tag }}
      #  run: |
      #    docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
      #    docker push ${TARGET_IMAGE}
